Pull request from karopawil's fork
fsaintjacques/disruptor-- pull request #39
Opened 2017-06-19 18:35 UTC by karopawil

Can have a look when you have time.

2017-06-19 21:06 UTC, tvdijk requested changes
I would love to be able to take some of these changes, but I'm concerned that these fixes are mixed up with functional changes which required interface changes. Is there any way you can split this out?

2017-06-19 21:06 UTC, tvdijk commented on disruptor/claim_strategy.h
> +  size_t N;
"N" is not very expressive, and doesn't follow the naming convention used. I would call this "buffer_size_".

2017-06-19 21:06 UTC, tvdijk commented on disruptor/claim_strategy.h
> +                            int64_t cursor, int required_capacity = 1) {
cursor is unused?

2017-06-19 21:06 UTC, tvdijk commented on disruptor/claim_strategy.h
> +    cursor.set_sequence(sequence);
What prompted this change?

2017-06-19 21:06 UTC, tvdijk commented on disruptor/ring_buffer.h
> +size_t kDefaultRingBufferSize = 1024;
Could still be const, no?

2017-06-19 21:06 UTC, tvdijk commented on disruptor/ring_buffer.h
> +  T* events_;
Consider using a std::vector instead of a raw pointer.

2017-06-19 21:06 UTC, tvdijk commented on disruptor/sequencer.h
> +    // const int64_t new_cursor = cursor_.IncrementAndGet(delta);
What prompted this change?

2017-06-20 05:59 UTC, karopawil commented
Hi,

Thanks for the feedback.  Suggestions improvements are always welcome. Not even sure what is there is the final interface as I haven't looked into pipelines and diamond patterns.

1. As far as I am concerned N can be changed to buffer_size_.

2. cursor value is used in MultiThreadedStrategyEx (LMAX Disruptor). To keep the interface consistent. With MultiThreadedStrategyEx Claim strategy I get a higher throughput than MultiThreadedStrategy.

3. My experience is that atomic store is much more efficient that fetch_add. In my tests I get a much higher thruput (one knows what the next sequence should be for a slot, why do a fetch and add?). And I moved the cursor.set_sequence(sequence) to SynchronizePublishing because MultiThreadedStrategyEx is intrusive and changes the cursor in IncrementAndGet. So the cursor has been forwarded. The user in this case has to check

// Only required for claim strategy MultiThreadedStrategyEx as it changes
    // the cursor.
    available_seq = s.GetHighestPublishedSequence(next_seq, available_seq);

You can have  a look at LMAX Multiproducersequencer.

4. -constexpr size_t kDefaultRingBufferSize = 1024;
+size_t kDefaultRingBufferSize = 1024;
Could still be const, no?

Yes.

5. Consider using a std::vector instead of a raw pointer.

Can be done. A matter of taste as it is a static array and should not have any effect on the performance as long as the vector is created with the required size.

6.
// Publish an event and make it visible to {@link EventProcessor}s.
   //
   // @param sequence to be published.
   void Publish(const int64_t& sequence, size_t delta = 1) {
     claim_strategy_.SynchronizePublishing(sequence, cursor_, delta);
-    const int64_t new_cursor = cursor_.IncrementAndGet(delta);
+    // const int64_t new_cursor = cursor_.IncrementAndGet(delta);
What prompted this change?

Explained above. You could change it back to IncrementAndGet and compare the throughput. example.cc can be used for that purpose.

2017-06-21 13:09 UTC, fsaintjacques commented
It'll help if we could fix travis, I'm not even sure this compile :)

2017-06-21 13:23 UTC, karopawil commented
I can compile this with gcc 5.4 and VS2015. What needs to be done for travis?

2017-06-21 13:29 UTC, karopawil commented
I'll fix up my fork travis build. have to learn about it first.

2017-06-21 16:31 UTC, karopawil commented
gcc 5.0 travis build works. clang 3.8 fails. No idea.

$ cd ${TRAVIS_BUILD_DIR} && tools/test
-- The CXX compiler identification is Clang 3.8.0
-- Check for working CXX compiler: /usr/bin/clang++-3.8
-- Check for working CXX compiler: /usr/bin/clang++-3.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   unit_test_framework
Coveralls: Using alternate CMake script dir: /home/travis/build/karopawil/disruptor--/tools/coveralls-cmake/cmake
COVERALLS UPLOAD: ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/build/karopawil/disruptor--/build
Scanning dependencies of target claim_strategy_test_bin
[ 11%] Building CXX object CMakeFiles/claim_strategy_test_bin.dir/test/claim_strategy_test.cc.o
In file included from /home/travis/build/karopawil/disruptor--/test/claim_strategy_test.cc:29:
In file included from /usr/include/boost/test/unit_test.hpp:19:
In file included from /usr/include/boost/test/test_tools.hpp:19:
In file included from /usr/include/boost/test/predicate_result.hpp:20:
In file included from /usr/include/boost/test/utils/wrap_stringstream.hpp:26:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/sstream:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/istream:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ios:40:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/char_traits.h:39:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algobase.h:739:11: error: 
      overload resolution selected deleted operator '='

2017-06-21 16:59 UTC, karopawil commented
Think gcc boost is getting used with clang. Anyway I have had enough for today.

2017-06-22 13:26 UTC, karopawil commented
Got a working travis script for clang 3.6, 3.8 and gcc 5, 6.

2018-03-20 07:17 UTC, karopawil commented
There are just too many changes to the interface. Not compatible.

2018-03-20 07:17 UTC, closed without merging